function VDPfig
    % Определяем глобальные переменные:
    global hFig hAxes
    global hEd1 hEd2 hEd3
    global hBut1 hBut2
    global hTxt1 hTxt2 hTxt3 hTxt4
    % Определяем окно и оси координат:
    hFig=figure('Position',[100 100 550 300]);
    hAxes=axes('Parent',hFig,'Color',[1 1 1], ...
    'Units','pixels','Position',[20 55 510 230], ...
    'FontSize',10,'Visible','off');
    % Определяем три редактируемых поля:
    hEd1=uicontrol(hFig,'Style','edit', ...
    'BackgroundColor',[1 1 1],'Position',[435 220 100 30], ...
    'HorizontalAlignment','left');
    hEd2=uicontrol(hFig,'Style','edit', ...
    'BackgroundColor',[1 1 1],'Position',[435 150 100 30], ...
    'HorizontalAlignment','left');
    hEd3=uicontrol(hFig,'Style','edit', ...
    'BackgroundColor',[1 1 1],'Position',[435 80 100 30], ...
    'HorizontalAlignment','left');
    % Вводим две кнопки:
    hBut1=uicontrol(hFig,'Style','pushbutton', ...
    'Position',[435 15 100 40],'String','Go', ...
    'Callback','GoCallback');
    % Вторая кнопка невидима:
    hBut2=uicontrol(hFig,'Style','pushbutton', ...
    'Position',[240 5 90 25],'String','Return', ...
    'Callback','ReturnCallback','Visible','off');
    % Вводим четыре не редактируемых текстовых поля:
    hTxt1=uicontrol(hFig,'Style','text', ...
    'BackgroundColor',[0.7 0.7 0.7],'Position',[20 15 400 270], ...
    'FontName','Arial','FontSize',20,'String', ...
    {'Van Der Pol equation','ode15s solver'});
    hTxt2=uicontrol(hFig,'Style','text', ...
    'BackgroundColor',[0.7 0.7 0.7],'Position',[435 255 70 20], ...
    'String','Initial y');
    hTxt3=uicontrol(hFig,'Style','text', ...
    'BackgroundColor',[0.7 0.7 0.7],'Position',[435 185 70 20], ...
    'String','Initial y''');
    hTxt4=uicontrol(hFig,'Style','text', ...
    'BackgroundColor',[0.7 0.7 0.7],'Position',[435 115 70 20], ...
    'String','Time interval');
end

